name: task_management
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  http: ^1.4.0
  supabase_flutter: ^2.9.1
  intl: ^0.20.2
  table_calendar: ^3.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  socket_io_client: ^3.1.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/logo.png
